/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UGSINXviLci
 */


export function Component() {
  return (
    (<div
      className="relative grid w-full h-screen min-h-screen gap-0 md:grid-cols-2">
      <div
        className="flex flex-col items-center justify-center gap-4 p-4 text-center md:gap-0 md:grid md:items-start md:px-6 lg:gap-10">
        <div className="space-y-2">
          <h1
            className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">Phobia Quiz</h1>
          <p className="text-gray-500 md:text-xl dark:text-gray-400">
            Test your knowledge of phobias! You have 15 seconds to answer each question.
          </p>
        </div>
        <div className="flex items-center justify-center w-full md:justify-start">
          <div className="flex items-center space-x-2">
            <ArrowRightIcon className="h-4 w-4" />
            <p className="text-sm font-semibold tracking-wider">Question 1</p>
          </div>
          <div className="flex items-center space-x-2 ml-auto">
            <p className="text-sm font-semibold tracking-wider">Score:</p>
            <p className="text-sm font-semibold tracking-wider">0/10</p>
          </div>
        </div>
        <div className="w-full max-w-sm space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div
              className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
              <span className="absolute inset-y-0 left-0 flex items-center ml-4">
                <div />
              </span>
              <label className="pointer-events-none select-none" htmlFor="q1a1">
                <span className="text-sm font-medium">A) Arachnophobia (fear of spiders)</span>
              </label>
            </div>
            <div
              className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
              <span className="absolute inset-y-0 left-0 flex items-center ml-4">
                <div />
              </span>
              <label className="pointer-events-none select-none" htmlFor="q1a2">
                <span className="text-sm font-medium">B) Acrophobia (fear of heights)</span>
              </label>
            </div>
            <div
              className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
              <span className="absolute inset-y-0 left-0 flex items-center ml-4">
                <div />
              </span>
              <label className="pointer-events-none select-none" htmlFor="q1a3">
                <span className="text-sm font-medium">C) Ophidiophobia (fear of snakes)</span>
              </label>
            </div>
            <div
              className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
              <span className="absolute inset-y-0 left-0 flex items-center ml-4">
                <div />
              </span>
              <label className="pointer-events-none select-none" htmlFor="q1a4">
                <span className="text-sm font-medium">D) Claustrophobia (fear of confined spaces)</span>
              </label>
            </div>
          </div>
        </div>
      </div>
      <div className="flex items-center justify-center p-4 md:p-12">
        <div className="grid w-full max-w-sm gap-4 text-center">
          <div
            className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
            <span className="absolute inset-y-0 left-0 flex items-center ml-4">
              <div />
            </span>
            <label className="pointer-events-none select-none" htmlFor="q1a1">
              <span className="text-sm font-medium">A) Arachnophobia (fear of spiders)</span>
            </label>
          </div>
          <div
            className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
            <span className="absolute inset-y-0 left-0 flex items-center ml-4">
              <div />
            </span>
            <label className="pointer-events-none select-none" htmlFor="q1a2">
              <span className="text-sm font-medium">B) Acrophobia (fear of heights)</span>
            </label>
          </div>
          <div
            className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
            <span className="absolute inset-y-0 left-0 flex items-center ml-4">
              <div />
            </span>
            <label className="pointer-events-none select-none" htmlFor="q1a3">
              <span className="text-sm font-medium">C) Ophidiophobia (fear of snakes)</span>
            </label>
          </div>
          <div
            className="relative flex items-center p-4 rounded-lg border border-gray-200 bg-white shadow-sm cursor-pointer dark:border-gray-800 hover:shadow transition-transform hover:scale-105 dark:border-gray-800">
            <span className="absolute inset-y-0 left-0 flex items-center ml-4">
              <div />
            </span>
            <label className="pointer-events-none select-none" htmlFor="q1a4">
              <span className="text-sm font-medium">D) Claustrophobia (fear of confined spaces)</span>
            </label>
          </div>
        </div>
      </div>
    </div>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}
